Fix of JSONDecoder error, UI enhancement + questions feature added
AnasAber/NLP_Recruitment pull request #12
Opened 2024-09-09 13:36 UTC by AnasAber

This includes:
- the fix for the JSONDecoder error
- UI enhancement, mainly the Matching scores part
- Interview Question for the candidate are now available although with an issue, should be fixed asap

2024-09-09 15:21 UTC, bssayla requested changes
I will try the app after applying the changes

2024-09-09 15:21 UTC, bssayla commented on prompts/resume_prompts.py
> +# """
better remove this commented part if there is no need for them

2024-09-09 15:21 UTC, bssayla commented on src/app.py
> +
same for this part

2024-09-09 15:21 UTC, bssayla commented on src/models/__pycache__/functions.cpython-310.pyc
better add `/__pycache__/` to the `.gitignore` file to avoid pushing the binary files

2024-09-09 15:21 UTC, bssayla commented on src/models/functions.py
> +    # except Exception as e:
remove commented part

2024-09-09 16:13 UTC, AnasAber commented
Anything else?

2024-09-10 14:47 UTC, merged

2024-09-10 14:47 UTC, bssayla commented
LGTM